[package]
name = "testkit-binding"
version = "0.1.0"
authors = ["Sergey Kletsun <sergey.kletsun@gmail.com>"]

[lib]
crate-type = ["dylib"]

[dependencies]
jni = "0.10.2"
testkit = { path = "../testkit" }
